# .github/workflows/test.yml
name: Test Action

on: [workflow_dispatch]

jobs:
  test:
    runs-on: macos-latest
    steps:
      - name: Use upload-artifact
        uses: actions/upload-artifact@v3
        with:
          name: test
          path: .